### ISSUE TITLE
Streamline update process

### ISSUE THREAD

**Issue by standage** [BrendelGroup/xGDBvm#1]
I just took a moment to spin up a new VM based on the new v1.13 image. I followed the `quickstart` instructions, which still include the `update` command which attempts to do a Subversion update. Since we've moved to git now, I edited the `update` script and was about to commit my changes when I noticed this had already by done and saved to a new `update-vm` script, which does the appropriate git update from GitHub.

I suggest we overwrite the `update` script with the new `update-vm` script and lose the second copy. There's really no reason I can think of for maintaining multiple copies.

**Comment by standage** [comment]
I committed a patch for this on my VM, but got this when trying to push to my fork.

```
[standage@vm64-212 xGDBvm]$ git push https://github.com/standage/xGDBvm.git master
error: The requested URL returned error: 403 Forbidden while accessing https://github.com/standage/xGDBvm.git/info/refs

fatal: HTTP request failed
[standage@vm64-212 xGDBvm]$
```

**Comment by jduvick** [comment]
I will remove the `update` script in my next round of commits, leaving `update-vm` as the official one.
