### ISSUE TITLE
Dropdown menu displays 10th GDB incorrectly

### ISSUE THREAD

**Issue by jduvick** [BrendelGroup/xGDBvm#26]
The menu code mishandles 2 digit ID - see screenshot
![screen shot 2016-02-25 at 3 45 10 pm](https://cloud.githubusercontent.com/assets/5558443/13335512/1d33081c-dbd7-11e5-8595-a8df51ade424.png)

**Comment by standage** [comment]
Is this the first time we've turned the dial all the way up to 10? ;-)

**Comment by jduvick** [comment]
Now, 11 ! :D

**Comment by standage** [comment]
This one goes up to 11?

![spinal_tap_-_up_to_eleven](https://cloud.githubusercontent.com/assets/566823/13339590/e63feb56-dbf7-11e5-9a79-939404916d11.jpg)

**Comment by jduvick** [comment]
Fixed by correcting 'greater than' to 'greater than or equal to'!
https://github.com/BrendelGroup/xGDBvm/commit/6a679b3f6070dd811b5a9660ac6be6b173c858bf
