### ISSUE TITLE
Root ownership of the code on iPlant/CyVerse images

### ISSUE THREAD

**Issue by standage** [BrendelGroup/xGDBvm#8]
Having the xGDBvm repo under root ownership on the iPlant images makes for an awkward development environment: file management and git configuration must be done as the root user instead of the regular user.

I'm not sure what this accomplishes. It doesn't offer any "protection" from iPlant users: most will ignore the code anyway, and there is little to stop those that are curious from tinkering since they have root permissions. But perhaps there are some legitimate security concerns or other practical considerations that this permissions scheme addresses.

I brought this up recently in email, but figured I'd start a thread here so that the conversation doesn't slip through the cracks again.

And I don't really consider this a major issue that should affect any of our timelines, I just want to better understand why we're doing what we're doing.

**Comment by vpbrendel** [comment]
I think there are legitimate reasons why the code should be under root 
ownership on the VM - essentially the same reasons why most systems 
files are under root ownership.

Even for single-user VMs, this adds a layer of protection against 
accidental edits, as the user would have to switch to sudo before making 
changes.

More generally, it is simple to add users to a VM, and there is no 
reason to give all of them root privileges.

On 2/15/2016 12:42 PM, Daniel Standage wrote:

> Having the xGDBvm repo under root ownership on the xGDBvm images makes 
> for an awkward development environment: file management and git 
> configuration must be done as the root user instead of the regular user.
> 
> I'm not sure what this accomplishes. It doesn't offer any "protection" 
> from iPlant users: most will ignore the code anyway, and there is 
> little to stop those that are curious from tinkering since they have 
> root permissions. But perhaps there are some legitimate security 
> concerns or other practical considerations that this permissions 
> scheme addresses.
> 
> I brought this up recently in email, but figured I'd start a thread 
> here so that the conversation doesn't slip through the cracks again.
> 
> And I don't really consider this a major issue that should affect any 
> of our timelines, I just want to better understand why we're doing 
> what we're doing.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/BrendelGroup/xGDBvm/issues/8.

## 

Volker Brendel
Professor of Biology and Computer Science
Indiana University
Department of Biology & School of Informatics and Computing
212 South Hawthorne Drive
Simon Hall 205C
Bloomington, IN 47405

Tel.: (812) 855-7074
http://brendelgroup.org/

**Comment by standage** [comment]
Ok, fair points.
